// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroes.Repositories;

#nullable disable

namespace SuperHeroes.Repositories.Migrations
{
    [DbContext(typeof(SuperheroesDbContext))]
    partial class SuperheroesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperHeroes.Repositories.UserFavouriteSuperhero", b =>
                {
                    b.Property<string>("UserToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SuperheroId")
                        .HasColumnType("int");

                    b.HasKey("UserToken", "SuperheroId");

                    b.ToTable("UserFavouriteSuperheroes");
                });
#pragma warning restore 612, 618
        }
    }
}
